# Corrects the discrepancy in category numbering between the DEMETR dataset
# (https://github.com/marzenakrp/demetr/tree/main/dataset) and the DEMETR
# paper (https://arxiv.org/abs/2210.13746). The discrepency appears to be
# because categories were re-classified/re-ordered for publication.
# Dataset category is the key and paper category is the value.
20: 34
21: 20
22: 21
23: 22
24: 23
25: 24
26: 25
27: 26
28: 27
29: 28
30: 29
31: 30
32: 31
33: 32
34: 33
